name: Destroy Gruen

on:
  workflow_run:
    workflows: ["CD Workflow"]
    branches: 
      - main
    types: 
      - completed

jobs:

  change_traffic:
    name: Change Traffic
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Cluster/AWS/Instances
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Sturmschwalbe84/infrastructure
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform traffic
        id: traffic
        run: terraform apply -var="Traffic=blue" -auto-approve

  destroy:
    name: Destroy Gruen
    runs-on: ubuntu-latest
    needs: change_traffic
    defaults:
      run:
        working-directory: Cluster/AWS/ECS_Green
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Sturmschwalbe84/infrastructure
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform destroy
      id: destroy
      run: terraform destroy -auto-approve