name: Destroy Infrastructure

on: 
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: true 

jobs:
  notification:
    uses: Sturmschwalbe84/testing/.github/workflows/notifications.yml@main
    with: 
      message: "*${{ github.actor }}* is trying to destroy *dev* environment because of *${{ github.event.inputs.reason }}*.\n\n[Link to the action.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    secrets: 
      token: ${{ secrets.TELEGRAM_TOKEN }}
      to: ${{ secrets.TELEGRAM_TO }}
      
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    needs: notification
    environment: 
      name: release 
    strategy:
      max-parallel: 1
      matrix:
        terraform_working_dir: [Cluster/AWS/ECS_Blue, Cluster/AWS/Instances, Cluster/AWS/VPC]
    defaults:
      run:
        working-directory: ${{ matrix.terraform_working_dir }}
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Sturmschwalbe84/infrastructure
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform destroy
      id: destroy
      run: terraform destroy -auto-approve
      continue-on-error: true


    
