name: Notifications test

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person'
        required: true
      reason:
        description: 'Reason'
        required: true 
jobs:
  notify:
    name: Notify about destroy
    runs-on: ubuntu-latest
    steps:

    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: "The ${{ github.events.inputs.name }} is trying to destroy dev because of ${{ github.events.inputs.reason }}." 

    - run: echo ${{ github.events.inputs.name }}
