name: Redirect Traffic 
env:                                      
  DEV_REPOSITORY: python-app-dev       
  IMAGE_TAG: "${{ github.sha }}"
on: 
  workflow_dispatch:
    inputs:
      traffic:
        description: 'Traffic'
        required: true 
      reason:
        description: 'Reason'
        required: true 
  
jobs: 
  redirect_notification:
    name: Traffic Notification 
  #  if: ${{ github.event.inputs.traffic }} == 'blue' || ${{ github.event.inputs.traffic }} == 'blue-80' || ${{ github.event.inputs.traffic }} == 'split' || ${{ github.event.inputs.traffic }} == 'gren-80' || ${{ github.event.inputs.traffic }} == 'green'
    uses: Sturmschwalbe84/testing/.github/workflows/notifications.yml@main
    with: 
      message: "*${{ github.actor }}* requested traffic redirection to '*${{ github.event.inputs.traffic }}*' in *${{ github.workflow }}* because of '*${{ github.event.inputs.reason }}*'.\n\n[Link to the action.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      body:    "${{ github.actor }} requested traffic redirection to '${{ github.event.inputs.traffic }}' in ${{ github.workflow }} because of '${{ github.event.inputs.reason }}'.\n\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      subject: Notification about ${{ github.workflow }} redirection
    secrets: 
      token: ${{ secrets.TELEGRAM_TOKEN }}
      to: ${{ secrets.TELEGRAM_TO }}
      mail_username: ${{ secrets.MAIL_USERNAME }}
      mail_password: ${{ secrets.MAIL_PASSWORD }}  

  redirect_traffic:
    name: Redirect Traffic
   # if: ${{ github.event.inputs.traffic }} == 'blue' || ${{ github.event.inputs.traffic }} == 'blue-80' || ${{ github.event.inputs.traffic }} == 'split' || ${{ github.event.inputs.traffic }} == 'green-80' || ${{ github.event.inputs.traffic }} == 'green'
    needs: redirect_notification
    runs-on: ubuntu-latest
    environment:
      name: staging
    defaults:
      run:
        working-directory: Cluster/AWS/Instances
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Sturmschwalbe84/infrastructure
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform traffic
        id: traffic
        run: terraform apply -var="Traffic=${{ github.event.inputs.traffic }}" -auto-approve
